python3 src/tests/test_textnode.py
python3 src/tests/test_htmlnode.py
python3 src/tests/test_leafnode.py
python3 src/tests/test_parentnode.py
python3 src/tests/test_split_delimiter.py
python3 src/tests/test_extract_markdown.py
python3 src/tests/test_split_img_link.py
python3 src/tests/test_text_to_textnodes.py
python3 src/tests/test_markdown_to_blocks.py
python3 src/tests/test_block_to_block_type.py
python3 src/tests/test_markdown_to_html_node.py
python3 src/tests/test_extract_title.py